name = "Autrans"
uuid = "1f02543f-5e56-4038-b276-ee84bbffedc8"
authors = ["atthom <thom.jalabert@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BenchmarkTools = "1.6.0"
Chain = "0.5.0"
DataFrames = "1.5.0"
DataStructures = "0.18.15"
HTTP = "1.10.8"
HiGHS = "1.14.0"
JuMP = "1.24.0"
OrderedCollections = "1.8.1"
Oxygen = "1.5.13"
Revise = "3.6.5"
StatsBase = "0.34.0"
